package DaRubyMiner360.moddingschool;

import DaRubyMiner360.moddingschool.item.ItemCheeseArmor;
import DaRubyMiner360.moddingschool.item.ItemCheeseAxe;
import DaRubyMiner360.moddingschool.item.ItemCheeseHoe;
import DaRubyMiner360.moddingschool.item.ItemCheesePickaxe;
import DaRubyMiner360.moddingschool.item.ItemCheeseShovel;
import DaRubyMiner360.moddingschool.item.ItemCheeseSword;
import DaRubyMiner360.moddingschool.item.ItemEmeraldArmor;
import DaRubyMiner360.moddingschool.item.ItemEmeraldAxe;
import DaRubyMiner360.moddingschool.item.ItemEmeraldHoe;
import DaRubyMiner360.moddingschool.item.ItemEmeraldPickaxe;
import DaRubyMiner360.moddingschool.item.ItemEmeraldShovel;
import DaRubyMiner360.moddingschool.item.ItemEmeraldSword;
import DaRubyMiner360.moddingschool.item.ItemObsidianArmor;
import DaRubyMiner360.moddingschool.item.ItemObsidianAxe;
import DaRubyMiner360.moddingschool.item.ItemObsidianHoe;
import DaRubyMiner360.moddingschool.item.ItemObsidianPickaxe;
import DaRubyMiner360.moddingschool.item.ItemObsidianShovel;
import DaRubyMiner360.moddingschool.item.ItemObsidianSword;
import DaRubyMiner360.moddingschool.item.ItemPaladusArmor;
import DaRubyMiner360.moddingschool.item.ItemRubyArmor;
import DaRubyMiner360.moddingschool.item.ItemRubyAxe;
import DaRubyMiner360.moddingschool.item.ItemRubyBroadword;
import DaRubyMiner360.moddingschool.item.ItemRubyDrill;
import DaRubyMiner360.moddingschool.item.ItemRubyHamaxe;
import DaRubyMiner360.moddingschool.item.ItemRubyHammer;
import DaRubyMiner360.moddingschool.item.ItemRubyHoe;
import DaRubyMiner360.moddingschool.item.ItemRubyMegaDrill;
import DaRubyMiner360.moddingschool.item.ItemRubyMegaHammer;
import DaRubyMiner360.moddingschool.item.ItemRubyPickaxe;
import DaRubyMiner360.moddingschool.item.ItemRubyShield;
import DaRubyMiner360.moddingschool.item.ItemRubyShovel;
import DaRubyMiner360.moddingschool.item.ItemRubySpear;
import DaRubyMiner360.moddingschool.item.ItemRubySword;
import DaRubyMiner360.moddingschool.item.ItemUltimaArmor;
import DaRubyMiner360.moddingschool.item.ItemUltimaAxe;
import DaRubyMiner360.moddingschool.item.ItemUltimaBow;
import DaRubyMiner360.moddingschool.item.ItemUltimaHoe;
import DaRubyMiner360.moddingschool.item.ItemUltimaPickaxe;
import DaRubyMiner360.moddingschool.item.ItemUltimaShovel;
import DaRubyMiner360.moddingschool.item.ItemUltimaSword;
import DaRubyMiner360.moddingschool.item.ItemUnknownTextureArmor;
import DaRubyMiner360.moddingschool.item.ItemUnknownTextureAxe;
import DaRubyMiner360.moddingschool.item.ItemUnknownTextureHoe;
import DaRubyMiner360.moddingschool.item.ItemUnknownTexturePickaxe;
import DaRubyMiner360.moddingschool.item.ItemUnknownTextureShovel;
import DaRubyMiner360.moddingschool.item.ItemUnknownTextureSword;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.EnumHelper;

@Mod(modid = "moddingschool", name = "Modding School", version = "1.0")
public class ModdingSchool {
	
	public static Item cheesePickaxe;
	public static Item cheeseAxe;
	public static Item cheeseShovel;
	public static Item cheeseHoe;
	public static Item cheeseSword;
	public static Item emeraldPickaxe;
	public static Item emeraldAxe;
	public static Item emeraldShovel;
	public static Item emeraldHoe;
	public static Item emeraldSword;
	public static Item rubyPickaxe;
	public static Item rubyAxe;
	public static Item rubyShovel;
	public static Item rubyHoe;
	public static Item rubySword;
	public static Item obsidianPickaxe;
	public static Item obsidianAxe;
	public static Item obsidianShovel;
	public static Item obsidianHoe;
	public static Item obsidianSword;
	public static Item unknownTexturePickaxe;
	public static Item unknownTextureAxe;
	public static Item unknownTextureShovel;
	public static Item unknownTextureHoe;
	public static Item unknownTextureSword;
	public static Item ultimaPickaxe;
	public static Item ultimaAxe;
	public static Item ultimaShovel;
	public static Item ultimaHoe;
	public static Item ultimaSword;
	
	public static Item rubyHammer;
	public static Item rubyMegaHammer;
	public static Item rubyHamaxe;
	public static Item rubyBroadsword;
	public static Item rubyDrill;
	public static Item rubyMegaDrill;
	public static Item rubySpear;
	public static Item ultimaBow;
	
	public static Item cheeseHelmet;
	public static Item cheeseChestplate;
	public static Item cheeseLeggings;
	public static Item cheeseBoots;
	public static Item emeraldHelmet;
	public static Item emeraldChestplate;
	public static Item emeraldLeggings;
	public static Item emeraldBoots;
	public static Item rubyHelmet;
	public static Item rubyChestplate;
	public static Item rubyLeggings;
	public static Item rubyBoots;
	public static Item obsidianHelmet;
	public static Item obsidianChestplate;
	public static Item obsidianLeggings;
	public static Item obsidianBoots;
	public static Item unknownTextureHelmet;
	public static Item unknownTextureChestplate;
	public static Item unknownTextureLeggings;
	public static Item unknownTextureBoots;
	public static Item paladusHelmet;
	public static Item paladusChestplate;
	public static Item ultimaHelmet;
	public static Item ultimaChestplate;
	public static Item ultimaLeggings;
	public static Item ultimaBoots;
	
	public static final Item.ToolMaterial cheeseToolMaterial = EnumHelper.addToolMaterial("cheeseToolMaterial", 1, 386, 3.0F, 1.0F, 2);
	public static final Item.ToolMaterial emeraldToolMaterial = EnumHelper.addToolMaterial("emeraldToolMaterial", 3, 1600, 8.0F, 3.0F, 10);
	public static final Item.ToolMaterial rubyToolMaterial = EnumHelper.addToolMaterial("rubyToolMaterial", 4, 2175, 10.0F, 4.0F, 15);
	public static final Item.ToolMaterial obsidianToolMaterial = EnumHelper.addToolMaterial("obsidianToolMaterial", 5, 3000, 12.0F, 4.0F, 17);
	public static final Item.ToolMaterial unknownTextureToolMaterial = EnumHelper.addToolMaterial("unknownTextureToolMaterial", 6, 5000, 15.0F, 4.0F, 20);
	public static final Item.ToolMaterial ultimaToolMaterial = EnumHelper.addToolMaterial("ultimaToolMaterial", 7, 10000, 23.0F, 4.0F, 23);
	
	public static final Item.ToolMaterial rubyHammerToolMaterial = EnumHelper.addToolMaterial("rubyHammerToolMaterial", 5, 3500, 14.0F, 8.0F, 18);
	public static final Item.ToolMaterial rubyMegaHammerToolMaterial = EnumHelper.addToolMaterial("rubyMegaHammerToolMaterial", 6, 5000, 18.0F, 14.0F, 21);
	public static final Item.ToolMaterial rubyHamaxeToolMaterial = EnumHelper.addToolMaterial("rubyHamaxeToolMaterial", 5, 4250, 13.0F, 10.0F, 18);
	public static final Item.ToolMaterial rubyBroadswordToolMaterial = EnumHelper.addToolMaterial("rubyBroadswordToolMaterial", 4, 4000, 10.0F, 8.5F, 21);
	public static final Item.ToolMaterial rubyDrillToolMaterial = EnumHelper.addToolMaterial("rubyDrillToolMaterial", 5, 3500, 15.0F, 5.0F, 18);
	public static final Item.ToolMaterial rubyMegaDrillToolMaterial = EnumHelper.addToolMaterial("rubyMegaDrillToolMaterial", 6, 5000, 20.0F, 7.0F, 21);
	public static final Item.ToolMaterial rubySpearToolMaterial = EnumHelper.addToolMaterial("rubySpearToolMaterial", 4, 3975, 10.0F, 6.0F, 20);
	public static final Item.ToolMaterial ultimaBowToolMaterial = EnumHelper.addToolMaterial("ultimaBowToolMaterial", 7, 10000, 23.0F, 7.0F, 23);
	
	public static final ItemArmor.ArmorMaterial cheeseArmorMaterial = EnumHelper.addArmorMaterial("cheeseArmorMaterial", 983, new int[]{2,7,5,3}, 2);
	public static final ItemArmor.ArmorMaterial emeraldArmorMaterial = EnumHelper.addArmorMaterial("emeraldArmorMaterial", 3500, new int[]{6,21,15,9}, 10);
	public static final ItemArmor.ArmorMaterial rubyArmorMaterial = EnumHelper.addArmorMaterial("rubyArmorMaterial", 5628, new int[]{8,28,20,12}, 15);
	public static final ItemArmor.ArmorMaterial obsidianArmorMaterial = EnumHelper.addArmorMaterial("obsidianArmorMaterial", 8000, new int[]{11,31,23,15}, 17);
	public static final ItemArmor.ArmorMaterial unknownTextureArmorMaterial = EnumHelper.addArmorMaterial("unknownTextureArmorMaterial", 11000, new int[]{16,36,28,20}, 30);
	public static final ItemArmor.ArmorMaterial paladusArmorMaterial = EnumHelper.addArmorMaterial("paladusArmorMaterial", 200000, new int[]{50,50,0,0}, 50);
	public static final ItemArmor.ArmorMaterial ultimaArmorMaterial = EnumHelper.addArmorMaterial("ultimaArmorMaterial", 150000, new int[]{33,33,33,33}, 33);
	
	public static Item itemTable;
	public static Block blockUltimaBlock;
	public static Item itemUltimaStick;
	public static Item itemChair;
	public static Block blockRuby_Ore;
	public static Item itemRuby;
	public static Item itemRubyNugget;
	public static Block blockRuby_Block;
	public static Block blockDaRubyMiner360_Skull;
	public static Block blockMrCrayfish_Skull;
	public static Item itemEnder_Dragon_Spawn_Egg;
	public static Item itemWither_Boss_Spawn_Egg;
	public static Item itemIron_Golem_Spawn_Egg;
	public static Item itemSnow_Golem_Spawn_Egg;
	public static Block blockUnknown_Texture_Ore;
	public static Item itemUnknown_Texture_Ingot;
	public static Item itemUnknownTextureNugget;
	public static Block blockUnknown_Texture_Block;
	public static Block blockError404Block;
	public static Block blockCheeseOre;
	public static Block blockNetherCheeseOre;
	public static Block blockEndCheeseOre;
	public static Item itemCheese;
	public static Item itemDirtyCheese;
	public static Item itemOverdoneCheese;
	public static Item itemBurntCheese;
	public static Item itemCheeseStick;
	public static Block blockCheeseBlock;
	public static Item itemGrilledCheese;
	public static Item itemEmerald_Apple;
	public static Item itemSuper_Emerald_Apple;
	public static Item itemEnchanted_Emerald_Apple;
	public static Item itemSuper_Enchanted_Emerald_Apple;
	public static Item itemYoullBeDarned;
	public static Block blockSoulAlter;
	public static Item itemGhastBaby;
	public static Item itemDiamondNugget;
	public static Item itemEmeraldNugget;
	public static Item itemObsidianNugget;
	public static Item itemSoulTear;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		//Item/Block init and registering
		//Config handling
		itemTable = new ItemTable().setUnlocalizedName("ItemTable").setTextureName("moddingschool:itemtable_small").setCreativeTab(tabModdingSchool);
		blockUltimaBlock = new BlockUltimaBlock(Material.iron).setBlockName("blockUltimaBlock").setBlockTextureName("moddingschool:blockUltimaBlock").setCreativeTab(tabModdingSchool);
		itemUltimaStick = new ItemUltimaStick().setUnlocalizedName("ItemUltimaStick").setTextureName("moddingschool:itemultimastick").setCreativeTab(tabModdingSchool);
		itemChair = new ItemChair().setUnlocalizedName("ItemChair").setTextureName("moddingschool:itemchair_small").setCreativeTab(tabModdingSchool);
		blockRuby_Ore = new BlockRuby_Ore(Material.iron).setBlockName("BlockRuby_Ore").setBlockTextureName("moddingschool:blockruby_ore").setCreativeTab(tabModdingSchool);
		itemRuby = new ItemRuby().setUnlocalizedName("ItemRuby").setTextureName("moddingschool:itemruby_small").setCreativeTab(tabModdingSchool);
		itemRubyNugget = new ItemRubyNugget().setUnlocalizedName("ItemRubyNugget").setTextureName("moddingschool:itemrubynugget").setCreativeTab(tabModdingSchool);
		blockRuby_Block = new BlockRuby_Block(Material.iron).setBlockName("BlockRuby_Block").setBlockTextureName("moddingschool:blockruby_block").setCreativeTab(tabModdingSchool);
		blockDaRubyMiner360_Skull = new BlockDaRubyMiner360_Skull(Material.carpet).setBlockName("BlockDaRubyMiner360_Skull").setBlockTextureName("moddingschool:blockdarubyminer360_Skull").setCreativeTab(tabModdingSchool);
		blockMrCrayfish_Skull = new BlockMrCrayfish_Skull(Material.carpet).setBlockName("BlockMrCrayfish_Skull").setBlockTextureName("moddingschool:blockmrcrayfish_skull").setCreativeTab(tabModdingSchool);
		blockUnknown_Texture_Ore = new BlockUnknown_Texture_Ore(Material.iron).setBlockName("BlockUnknown_Texture_Ore").setBlockTextureName("moddingschool:blockunknown_texture_ore").setCreativeTab(tabModdingSchool);
		itemUnknown_Texture_Ingot = new ItemUnknown_Texture_Ingot().setUnlocalizedName("ItemUnknown_Texture_Ingot").setTextureName("moddingschool:itemunknown_texture_ingot").setCreativeTab(tabModdingSchool);
		itemUnknownTextureNugget = new ItemUnknownTextureNugget().setUnlocalizedName("ItemUnknownTextureNugget").setTextureName("moddingschool:itemunknowntexturenugget").setCreativeTab(tabModdingSchool);
		blockUnknown_Texture_Block = new BlockUnknown_Texture_Block(Material.iron).setBlockName("BlockUnknown_Texture_Block").setCreativeTab(tabModdingSchool);
		blockError404Block = new BlockError404Block(Material.iron).setBlockName("BlockError404Block").setBlockTextureName("moddingschool:blockerror404block").setCreativeTab(tabModdingSchool);
		itemEnder_Dragon_Spawn_Egg = new ItemEnder_Dragon_Spawn_Egg().setUnlocalizedName("ItemEnder_Dragon_Spawn_Egg").setTextureName("moddingschool:itemender_dragon_spawn_egg").setCreativeTab(tabModdingSchool);
		itemWither_Boss_Spawn_Egg = new ItemWither_Boss_Spawn_Egg().setUnlocalizedName("ItemWither_Boss_Spawn_Egg").setTextureName("moddingschool:itemwither_boss_spawn_egg").setCreativeTab(tabModdingSchool);
		itemIron_Golem_Spawn_Egg = new ItemIron_Golem_Spawn_Egg().setUnlocalizedName("ItemIron_Golem_Spawn_Egg").setTextureName("moddingschool:itemiron_golem_spawn_egg").setCreativeTab(tabModdingSchool);
		itemSnow_Golem_Spawn_Egg = new ItemSnow_Golem_Spawn_Egg().setUnlocalizedName("ItemSnow_Golem_Spawn_Egg").setTextureName("moddingschool:itemsnow_golem_spawn_egg").setCreativeTab(tabModdingSchool);
		itemYoullBeDarned = new ItemYoullBeDarned().setUnlocalizedName("ItemYoullBeDarned").setTextureName("moddingschool:itemyoullbedarned").setCreativeTab(tabModdingSchool);
		blockSoulAlter = new BlockSoulAlter(Material.iron).setBlockName("BlockSoulAlter").setBlockTextureName("moddingschool:blocksoulalter").setCreativeTab(tabModdingSchool);
		itemGhastBaby = new ItemGhastBaby().setUnlocalizedName("ItemGhastBaby").setTextureName("moddingschool:itemghastbaby").setCreativeTab(tabModdingSchool);
		blockCheeseOre = new BlockCheeseOre(Material.cake).setBlockName("BlockCheeseOre").setBlockTextureName("moddingschool:blockcheeseore").setCreativeTab(tabModdingSchool);
		blockNetherCheeseOre = new BlockNetherCheeseOre(Material.cake).setBlockName("BlockNetherCheeseOre").setBlockTextureName("moddingschool:blocknethercheeseore").setCreativeTab(tabModdingSchool);
		blockEndCheeseOre = new BlockEndCheeseOre(Material.cake).setBlockName("BlockEndCheeseOre").setBlockTextureName("moddingschool:blockendcheeseore").setCreativeTab(tabModdingSchool);
		itemCheese = new ItemFood(8, 0.5F, false).setUnlocalizedName("ItemCheese").setTextureName("moddingschool:itemcheese").setCreativeTab(tabModdingSchool);
		itemDirtyCheese = new ItemFood(4, 0.25F, false).setUnlocalizedName("ItemDirtyCheese").setTextureName("moddingschool:itemdirtycheese").setCreativeTab(tabModdingSchool);
		itemOverdoneCheese = new ItemFood(4, 0.125F, false).setUnlocalizedName("ItemOverdoneCheese").setTextureName("moddingschool:itemoverdonecheese").setCreativeTab(tabModdingSchool);
		itemBurntCheese = new ItemFood(2, 0.2F, false).setUnlocalizedName("ItemBurntCheese").setTextureName("moddingschool:itemburntcheese").setCreativeTab(tabModdingSchool);
		itemCheeseStick = new ItemCheeseStick().setUnlocalizedName("ItemCheeseStick").setTextureName("blaze_rod").setCreativeTab(tabModdingSchool);
		blockCheeseBlock = new BlockCheeseBlock(Material.cake).setBlockName("BlockCheeseBlock").setBlockTextureName("moddingschool:blockcheeseblock").setCreativeTab(tabModdingSchool);
		itemGrilledCheese = new ItemFood(16, 1.0F, false).setUnlocalizedName("ItemGrilledCheese").setTextureName("moddingschool:itemgrilledcheese").setCreativeTab(tabModdingSchool);
		itemEmerald_Apple = new ItemFood(5, 1.0F, false).setUnlocalizedName("ItemEmerald_Apple").setTextureName("moddingschool:itememerald_apple").setCreativeTab(tabModdingSchool);
		itemSuper_Emerald_Apple = new ItemFood(10, 0.5F, false).setUnlocalizedName("ItemSuper_Emerald_Apple").setTextureName("moddingschool:itemsuper_emerald_apple").setCreativeTab(tabModdingSchool);
		itemEnchanted_Emerald_Apple = new ItemFood(15, 0.7F, false).setUnlocalizedName("ItemEnchanted_Emerald_Apple").setTextureName("moddingschool:itemenchanted_emerald_apple").setCreativeTab(tabModdingSchool);
		itemSuper_Enchanted_Emerald_Apple = new ItemFood(20, 1.0F, false).setUnlocalizedName("ItemSuper_Enchanted_Emerald_Apple").setTextureName("moddingschool:itemsuper_enchanted_emerald_apple").setCreativeTab(tabModdingSchool);
		itemDiamondNugget = new ItemDiamondNugget().setUnlocalizedName("ItemDiamondNugget").setTextureName("moddingschool:itemdiamondnugget").setCreativeTab(tabModdingSchool);
		itemEmeraldNugget = new ItemEmeraldNugget().setUnlocalizedName("ItemEmeraldNugget").setTextureName("moddingschool:itememeraldnugget").setCreativeTab(tabModdingSchool);
		itemObsidianNugget = new ItemObsidianNugget().setUnlocalizedName("ItemObsidianNugget").setTextureName("moddingschool:itemobsidiannugget").setCreativeTab(tabModdingSchool);
		
		cheesePickaxe = new ItemCheesePickaxe(cheeseToolMaterial).setUnlocalizedName("ItemCheesePickaxe").setTextureName("moddingschool:itemcheesepickaxe").setCreativeTab(tabModdingSchool);
		cheeseAxe = new ItemCheeseAxe(cheeseToolMaterial).setUnlocalizedName("ItemCheeseAxe").setTextureName("moddingschool:itemcheeseaxe").setCreativeTab(tabModdingSchool);
		cheeseShovel = new ItemCheeseShovel(cheeseToolMaterial).setUnlocalizedName("ItemCheeseShovel").setTextureName("moddingschool:itemcheeseshovel").setCreativeTab(tabModdingSchool);
		cheeseHoe = new ItemCheeseHoe(cheeseToolMaterial).setUnlocalizedName("ItemCheeseHoe").setTextureName("moddingschool:itemcheesehoe").setCreativeTab(tabModdingSchool);
		cheeseSword = new ItemCheeseSword(cheeseToolMaterial).setUnlocalizedName("ItemCheeseSword").setTextureName("moddingschool:itemcheesesword").setCreativeTab(tabModdingSchool);
		emeraldPickaxe = new ItemEmeraldPickaxe(emeraldToolMaterial).setUnlocalizedName("ItemEmeraldPickaxe").setTextureName("moddingschool:itememeraldpickaxe").setCreativeTab(tabModdingSchool);
		emeraldAxe = new ItemEmeraldAxe(emeraldToolMaterial).setUnlocalizedName("ItemEmeraldAxe").setTextureName("moddingschool:itememeraldaxe").setCreativeTab(tabModdingSchool);
		emeraldShovel = new ItemEmeraldShovel(emeraldToolMaterial).setUnlocalizedName("ItemEmeraldShovel").setTextureName("moddingschool:itememeraldshovel").setCreativeTab(tabModdingSchool);
		emeraldHoe = new ItemEmeraldHoe(emeraldToolMaterial).setUnlocalizedName("ItemEmeraldHoe").setTextureName("moddingschool:itememeraldhoe").setCreativeTab(tabModdingSchool);
		emeraldSword = new ItemEmeraldSword(emeraldToolMaterial).setUnlocalizedName("ItemEmeraldSword").setTextureName("moddingschool:itememeraldsword").setCreativeTab(tabModdingSchool);
		rubyPickaxe = new ItemRubyPickaxe(rubyToolMaterial).setUnlocalizedName("ItemRubyPickaxe").setTextureName("moddingschool:itemrubypickaxe").setCreativeTab(tabModdingSchool);
		rubyAxe = new ItemRubyAxe(rubyToolMaterial).setUnlocalizedName("ItemRubyAxe").setTextureName("moddingschool:itemrubyaxe").setCreativeTab(tabModdingSchool);
		rubyHammer = new ItemRubyHammer(rubyHammerToolMaterial).setUnlocalizedName("ItemRubyHammer").setTextureName("moddingschool:itemrubyhammer").setCreativeTab(tabModdingSchool);
		rubyMegaHammer = new ItemRubyMegaHammer(rubyMegaHammerToolMaterial).setUnlocalizedName("ItemRubyMegaHammer").setTextureName("moddingschool:itemrubymegahammer").setCreativeTab(tabModdingSchool);
		rubyHamaxe = new ItemRubyHamaxe(rubyHamaxeToolMaterial).setUnlocalizedName("ItemRubyHamaxe").setTextureName("moddingschool:itemrubyhamaxe").setCreativeTab(tabModdingSchool);
		rubyShovel = new ItemRubyShovel(rubyToolMaterial).setUnlocalizedName("ItemRubyShovel").setTextureName("moddingschool:itemrubyshovel").setCreativeTab(tabModdingSchool);
		rubyHoe = new ItemRubyHoe(rubyToolMaterial).setUnlocalizedName("ItemRubyHoe").setTextureName("moddingschool:itemrubyhoe").setCreativeTab(tabModdingSchool);
		rubySword = new ItemRubySword(rubyToolMaterial).setUnlocalizedName("ItemRubySword").setTextureName("moddingschool:itemrubysword").setCreativeTab(tabModdingSchool);
		rubyBroadsword = new ItemRubyBroadword(rubyBroadswordToolMaterial).setUnlocalizedName("ItemRubyBroadsword").setTextureName("moddingschool:itemrubybroadsword").setCreativeTab(tabModdingSchool);		
		rubyDrill = new ItemRubyDrill(rubyDrillToolMaterial).setUnlocalizedName("ItemRubyDrill").setTextureName("moddingschool:itemrubydrill").setCreativeTab(tabModdingSchool);
		rubyMegaDrill = new ItemRubyMegaDrill(rubyMegaDrillToolMaterial).setUnlocalizedName("ItemRubyMegaDrill").setTextureName("moddingschool:itemrubymegadrill").setCreativeTab(tabModdingSchool);
		rubySpear = new ItemRubySpear(rubySpearToolMaterial).setUnlocalizedName("ItemRubySpear").setTextureName("moddingschool:itemrubyspear").setCreativeTab(tabModdingSchool);
		obsidianPickaxe = new ItemObsidianPickaxe(obsidianToolMaterial).setUnlocalizedName("ItemObsidianPickaxe").setTextureName("moddingschool:itemobsidianpickaxe").setCreativeTab(tabModdingSchool);
		obsidianAxe = new ItemObsidianAxe(obsidianToolMaterial).setUnlocalizedName("ItemObsidianAxe").setTextureName("moddingschool:itemobsidianaxe").setCreativeTab(tabModdingSchool);
		obsidianShovel = new ItemObsidianShovel(obsidianToolMaterial).setUnlocalizedName("ItemObsidianShovel").setTextureName("moddingschool:itemobsidianshovel").setCreativeTab(tabModdingSchool);
		obsidianHoe = new ItemObsidianHoe(obsidianToolMaterial).setUnlocalizedName("ItemObsidianHoe").setTextureName("moddingschool:itemobsidianhoe").setCreativeTab(tabModdingSchool);
		obsidianSword = new ItemObsidianSword(obsidianToolMaterial).setUnlocalizedName("ItemObsidianSword").setTextureName("moddingschool:itemobsidiansword").setCreativeTab(tabModdingSchool);
		unknownTexturePickaxe = new ItemUnknownTexturePickaxe(unknownTextureToolMaterial).setUnlocalizedName("ItemUnknownTexturePickaxe").setTextureName("moddingschool:itemunknowntexturepickaxe").setCreativeTab(tabModdingSchool);
		unknownTextureAxe = new ItemUnknownTextureAxe(unknownTextureToolMaterial).setUnlocalizedName("ItemUnknownTextureAxe").setTextureName("moddingschool:itemunknowntextureaxe").setCreativeTab(tabModdingSchool);
		unknownTextureShovel = new ItemUnknownTextureShovel(unknownTextureToolMaterial).setUnlocalizedName("ItemUnknownTextureShovel").setTextureName("moddingschool:itemunknowntextureshovel").setCreativeTab(tabModdingSchool);
		unknownTextureHoe = new ItemUnknownTextureHoe(unknownTextureToolMaterial).setUnlocalizedName("ItemUnknownTextureHoe").setTextureName("moddingschool:itemunknowntexturehoe").setCreativeTab(tabModdingSchool);
		unknownTextureSword = new ItemUnknownTextureSword(unknownTextureToolMaterial).setUnlocalizedName("ItemUnknownTextureSword").setTextureName("moddingschool:itemunknowntexturesword").setCreativeTab(tabModdingSchool);		
		ultimaPickaxe = new ItemUltimaPickaxe(ultimaToolMaterial).setUnlocalizedName("ItemUltimaPickaxe").setTextureName("moddingschool:itemultimapickaxe").setCreativeTab(tabModdingSchool);
		ultimaAxe = new ItemUltimaAxe(ultimaToolMaterial).setUnlocalizedName("ItemUltimaAxe").setTextureName("moddingschool:itemultimaaxe").setCreativeTab(tabModdingSchool);
		ultimaShovel = new ItemUltimaShovel(ultimaToolMaterial).setUnlocalizedName("ItemUltimaShovel").setTextureName("moddingschool:itemultimashovel").setCreativeTab(tabModdingSchool);
		ultimaHoe = new ItemUltimaHoe(ultimaToolMaterial).setUnlocalizedName("ItemUltimaHoe").setTextureName("moddingschool:itemultimahoe").setCreativeTab(tabModdingSchool);
		ultimaSword = new ItemUltimaSword(ultimaToolMaterial).setUnlocalizedName("ItemUltimaSword").setTextureName("moddingschool:itemultimasword").setCreativeTab(tabModdingSchool);
		ultimaBow = new ItemUltimaBow(ultimaBowToolMaterial).setUnlocalizedName("ItemUltimaBow").setTextureName("moddingschool:itemultimabow").setCreativeTab(tabModdingSchool);
		
		cheeseHelmet = new ItemCheeseArmor(cheeseArmorMaterial, 0, 0).setUnlocalizedName("ItemCheeseHelmet").setTextureName("moddingschool:itemcheesehelmet").setCreativeTab(tabModdingSchool);
		cheeseChestplate = new ItemCheeseArmor(cheeseArmorMaterial, 0, 1).setUnlocalizedName("ItemCheeseChestplate").setTextureName("moddingschool:itemcheesechestplate").setCreativeTab(tabModdingSchool);
		cheeseLeggings = new ItemCheeseArmor(cheeseArmorMaterial, 0, 2).setUnlocalizedName("ItemCheeseLeggings").setTextureName("moddingschool:itemcheeseleggings").setCreativeTab(tabModdingSchool);
		cheeseBoots = new ItemCheeseArmor(cheeseArmorMaterial, 0, 3).setUnlocalizedName("ItemCheeseBoots").setTextureName("moddingschool:itemcheeseboots").setCreativeTab(tabModdingSchool);
		emeraldHelmet = new ItemEmeraldArmor(emeraldArmorMaterial, 0, 0).setUnlocalizedName("ItemEmeraldHelmet").setTextureName("moddingschool:itememeraldhelmet").setCreativeTab(tabModdingSchool);
		emeraldChestplate = new ItemEmeraldArmor(emeraldArmorMaterial, 0, 1).setUnlocalizedName("ItemEmeraldChestplate").setTextureName("moddingschool:itememeraldchestplate").setCreativeTab(tabModdingSchool);
		emeraldLeggings = new ItemEmeraldArmor(emeraldArmorMaterial, 0, 2).setUnlocalizedName("ItemEmeraldLeggings").setTextureName("moddingschool:itememeraldleggings").setCreativeTab(tabModdingSchool);
		emeraldBoots = new ItemEmeraldArmor(emeraldArmorMaterial, 0, 3).setUnlocalizedName("ItemEmeraldBoots").setTextureName("moddingschool:itememeraldboots").setCreativeTab(tabModdingSchool);
		rubyHelmet = new ItemRubyArmor(rubyArmorMaterial, 0, 0).setUnlocalizedName("ItemRubyHelmet").setTextureName("moddingschool:itemrubyhelmet").setCreativeTab(tabModdingSchool);
		rubyChestplate = new ItemRubyArmor(rubyArmorMaterial, 0, 1).setUnlocalizedName("ItemRubyChestplate").setTextureName("moddingschool:itemrubychestplate").setCreativeTab(tabModdingSchool);
		rubyLeggings = new ItemRubyArmor(rubyArmorMaterial, 0, 2).setUnlocalizedName("ItemRubyLeggings").setTextureName("moddingschool:itemrubyleggings").setCreativeTab(tabModdingSchool);
		rubyBoots = new ItemRubyArmor(rubyArmorMaterial, 0, 3).setUnlocalizedName("ItemRubyBoots").setTextureName("moddingschool:itemrubyboots").setCreativeTab(tabModdingSchool);
		obsidianHelmet = new ItemObsidianArmor(obsidianArmorMaterial, 0, 0).setUnlocalizedName("ItemObsidianHelmet").setTextureName("moddingschool:itemobsidianhelmet").setCreativeTab(tabModdingSchool);
		obsidianChestplate = new ItemObsidianArmor(obsidianArmorMaterial, 0, 1).setUnlocalizedName("ItemObsidianChestplate").setTextureName("moddingschool:itemobsidianchestplate").setCreativeTab(tabModdingSchool);
		obsidianLeggings = new ItemObsidianArmor(obsidianArmorMaterial, 0, 2).setUnlocalizedName("ItemObsidianLeggings").setTextureName("moddingschool:itemobsidianleggings").setCreativeTab(tabModdingSchool);
		obsidianBoots = new ItemObsidianArmor(obsidianArmorMaterial, 0, 3).setUnlocalizedName("ItemObsidianBoots").setTextureName("moddingschool:itemobsidianboots").setCreativeTab(tabModdingSchool);
		unknownTextureHelmet = new ItemUnknownTextureArmor(unknownTextureArmorMaterial, 0, 0).setUnlocalizedName("ItemUnknownTextureHelmet").setTextureName("moddingschool:itemunknowntexturehelmet").setCreativeTab(tabModdingSchool);
		unknownTextureChestplate = new ItemUnknownTextureArmor(unknownTextureArmorMaterial, 0, 1).setUnlocalizedName("ItemUnknownTextureChestplate").setTextureName("moddingschool:itemunknowntexturechestplate").setCreativeTab(tabModdingSchool);
		unknownTextureLeggings = new ItemUnknownTextureArmor(unknownTextureArmorMaterial, 0, 2).setUnlocalizedName("ItemUnknownTextureLeggings").setTextureName("moddingschool:itemunknowntextureleggings").setCreativeTab(tabModdingSchool);
		unknownTextureBoots = new ItemUnknownTextureArmor(unknownTextureArmorMaterial, 0, 3).setUnlocalizedName("ItemUnknownTextureBoots").setTextureName("moddingschool:itemunknowntextureboots").setCreativeTab(tabModdingSchool);
		paladusHelmet = new ItemPaladusArmor(paladusArmorMaterial, 0, 0).setUnlocalizedName("ItemPaladusHelmet").setTextureName("moddingschool:itempaladushelmet").setCreativeTab(tabModdingSchool);
		paladusChestplate = new ItemPaladusArmor(paladusArmorMaterial, 0, 1).setUnlocalizedName("ItemPaladusChestplate").setTextureName("moddingschool:itempaladuschestplate").setCreativeTab(tabModdingSchool);
		ultimaHelmet = new ItemUltimaArmor(ultimaArmorMaterial, 0, 0).setUnlocalizedName("ItemUltimaHelmet").setTextureName("moddingschool:itemultimahelmet").setCreativeTab(tabModdingSchool);
		ultimaChestplate = new ItemUltimaArmor(ultimaArmorMaterial, 0, 1).setUnlocalizedName("ItemUltimaChestplate").setTextureName("moddingschool:itemultimachestplate").setCreativeTab(tabModdingSchool);
		ultimaLeggings = new ItemUltimaArmor(ultimaArmorMaterial, 0, 2).setUnlocalizedName("ItemUltimaLeggings").setTextureName("moddingschool:itemultimaleggings").setCreativeTab(tabModdingSchool);
		ultimaBoots = new ItemUltimaArmor(ultimaArmorMaterial, 0, 3).setUnlocalizedName("ItemUltimaBoots").setTextureName("moddingschool:itemultimaboots").setCreativeTab(tabModdingSchool);
		
		
		
		GameRegistry.registerItem(itemTable, itemTable.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockUltimaBlock, blockUltimaBlock.getUnlocalizedName().substring(5));
		System.out.println(blockUltimaBlock.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemChair, itemChair.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockRuby_Ore, blockRuby_Ore.getUnlocalizedName().substring(5));
		System.out.println(blockRuby_Ore.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRuby, itemRuby.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRubyNugget, itemRubyNugget.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockRuby_Block, blockRuby_Block.getUnlocalizedName().substring(5));
		System.out.println(blockRuby_Block.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockDaRubyMiner360_Skull, blockDaRubyMiner360_Skull.getUnlocalizedName().substring(5));
		System.out.println(blockDaRubyMiner360_Skull.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockMrCrayfish_Skull, blockMrCrayfish_Skull.getUnlocalizedName().substring(5));
		System.out.println(blockMrCrayfish_Skull.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockUnknown_Texture_Ore, blockUnknown_Texture_Ore.getUnlocalizedName().substring(5));
		System.out.println(blockUnknown_Texture_Ore.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemUnknown_Texture_Ingot, itemUnknown_Texture_Ingot.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemUnknownTextureNugget, itemUnknownTextureNugget.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockUnknown_Texture_Block, blockUnknown_Texture_Block.getUnlocalizedName().substring(5));
		System.out.println(blockUnknown_Texture_Block.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockError404Block, blockError404Block.getUnlocalizedName().substring(5));
		System.out.println(blockError404Block.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnder_Dragon_Spawn_Egg, itemEnder_Dragon_Spawn_Egg.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemWither_Boss_Spawn_Egg, itemWither_Boss_Spawn_Egg.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemIron_Golem_Spawn_Egg, itemIron_Golem_Spawn_Egg.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemSnow_Golem_Spawn_Egg, itemSnow_Golem_Spawn_Egg.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemYoullBeDarned, itemYoullBeDarned.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockSoulAlter, blockSoulAlter.getUnlocalizedName().substring(5));
		System.out.println(blockSoulAlter.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemGhastBaby, itemGhastBaby.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemCheese, itemCheese.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemDirtyCheese, itemDirtyCheese.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemOverdoneCheese, itemOverdoneCheese.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemBurntCheese, itemBurntCheese.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemCheeseStick, itemCheeseStick.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockCheeseBlock, blockCheeseBlock.getUnlocalizedName().substring(5));
		System.out.println(blockCheeseBlock.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockCheeseOre, blockCheeseOre.getUnlocalizedName().substring(5));
		System.out.println(blockCheeseOre.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockNetherCheeseOre, blockNetherCheeseOre.getUnlocalizedName().substring(5));
		System.out.println(blockNetherCheeseOre.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(blockEndCheeseOre, blockEndCheeseOre.getUnlocalizedName().substring(5));
		System.out.println(blockEndCheeseOre.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemGrilledCheese, itemGrilledCheese.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEmerald_Apple, itemEmerald_Apple.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemSuper_Emerald_Apple, itemSuper_Emerald_Apple.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnchanted_Emerald_Apple, itemEnchanted_Emerald_Apple.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemSuper_Enchanted_Emerald_Apple, itemSuper_Enchanted_Emerald_Apple.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemDiamondNugget, itemDiamondNugget.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEmeraldNugget, itemEmeraldNugget.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemObsidianNugget, itemObsidianNugget.getUnlocalizedName().substring(5));
		
		GameRegistry.registerItem(cheesePickaxe, cheesePickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cheeseAxe, cheeseAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cheeseShovel, cheeseShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cheeseHoe, cheeseHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cheeseSword, cheeseSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldPickaxe, emeraldPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldAxe, emeraldAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldShovel, emeraldShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldHoe, emeraldHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldSword, emeraldSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyPickaxe, rubyPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyAxe, rubyAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyShovel, rubyShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyHoe, rubyHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubySword, rubySword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyHammer, rubyHammer.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyMegaHammer, rubyMegaHammer.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyHamaxe, rubyHamaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyBroadsword, rubyBroadsword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyDrill, rubyDrill.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyMegaDrill, rubyMegaDrill.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubySpear, rubySpear.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianPickaxe, obsidianPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianAxe, obsidianAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianShovel, obsidianShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianHoe, obsidianHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianSword, obsidianSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(unknownTexturePickaxe, unknownTexturePickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(unknownTextureAxe, unknownTextureAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(unknownTextureShovel, unknownTextureShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(unknownTextureHoe, unknownTextureHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(unknownTextureSword, unknownTextureSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaPickaxe, ultimaPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaAxe, ultimaAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaShovel, ultimaShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaHoe, ultimaHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaSword, ultimaSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaBow, ultimaBow.getUnlocalizedName().substring(5));
		
		GameRegistry.registerItem(cheeseHelmet, cheeseHelmet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cheeseChestplate, cheeseChestplate.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cheeseLeggings, cheeseLeggings.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cheeseBoots, cheeseBoots.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldHelmet, emeraldHelmet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldChestplate, emeraldChestplate.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldLeggings, emeraldLeggings.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldBoots, emeraldBoots.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyHelmet, rubyHelmet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyChestplate, rubyChestplate.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyLeggings, rubyLeggings.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyBoots, rubyBoots.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianHelmet, obsidianHelmet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianChestplate, obsidianChestplate.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianLeggings, obsidianLeggings.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianBoots, obsidianBoots.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(unknownTextureHelmet, unknownTextureHelmet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(unknownTextureChestplate, unknownTextureChestplate.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(unknownTextureLeggings, unknownTextureLeggings.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(unknownTextureBoots, unknownTextureBoots.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(paladusHelmet, paladusHelmet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(paladusChestplate, paladusChestplate.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaHelmet, ultimaHelmet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaChestplate, ultimaChestplate.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaLeggings, ultimaLeggings.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(ultimaBoots, ultimaBoots.getUnlocalizedName().substring(5));
		
		GameRegistry.registerWorldGenerator(new OreGeneration(), 0);
		
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
		//Proxy, TileEntity, entity, GUI and Packet Registering
		GameRegistry.addRecipe(new ItemStack(itemTable, 1), new Object[]{"WWW"," W "," W ", 'W', Blocks.planks});
		GameRegistry.addRecipe(new ItemStack(itemUltimaStick, 9), new Object[]{"UUU","USU","UUU", 'U', blockUltimaBlock, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(blockUltimaBlock, 8), new Object[]{"SSS","SSS","SSS", 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(itemEmerald_Apple, 1), new Object[]{"EEE","EAE","EEE", 'E', Items.emerald, 'A', Items.apple});
		GameRegistry.addRecipe(new ItemStack(itemSuper_Emerald_Apple, 1), new Object[]{"EEE","EAE","EEE", 'E', Items.emerald, 'A', itemEmerald_Apple});
		GameRegistry.addRecipe(new ItemStack(itemEnchanted_Emerald_Apple, 1), new Object[]{"EEE","EAE","EEE", 'E', Blocks.emerald_block, 'A', Items.apple});
		GameRegistry.addRecipe(new ItemStack(itemSuper_Enchanted_Emerald_Apple, 1), new Object[]{"EEE","EAE","EEE", 'E', Blocks.emerald_block, 'A', itemEnchanted_Emerald_Apple});
		GameRegistry.addRecipe(new ItemStack(cheesePickaxe, 1), new Object[]{"CCC"," S "," S ", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseAxe, 1), new Object[]{"CC ","CS "," S ", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseAxe, 1), new Object[]{" CC"," CS","  S", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseShovel, 1), new Object[]{"C  ","S  ","S  ", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseShovel, 1), new Object[]{" C "," S "," S ", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseShovel, 1), new Object[]{"  C","  S","  S", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseHoe, 1), new Object[]{"CC "," S "," S ", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseHoe, 1), new Object[]{" CC","  S","  S", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseSword, 1), new Object[]{"C  ","C  ","S  ", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseSword, 1), new Object[]{" C "," C "," S ", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(cheeseSword, 1), new Object[]{"  C","  C","  S", 'C', blockCheeseBlock, 'S', itemCheeseStick});
		GameRegistry.addRecipe(new ItemStack(emeraldPickaxe, 1), new Object[]{"CCC"," S "," S ", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldAxe, 1), new Object[]{"CC ","CS "," S ", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldAxe, 1), new Object[]{" CC"," CS","  S", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldShovel, 1), new Object[]{" C "," S "," S ", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldShovel, 1), new Object[]{"C  ","S  ","S  ", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldShovel, 1), new Object[]{"  C","  S","  S", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldHoe, 1), new Object[]{"CC "," S "," S ", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldHoe, 1), new Object[]{" CC","  S","  S", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldSword, 1), new Object[]{" C "," C "," S ", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldSword, 1), new Object[]{"C  ","C  ","S  ", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(emeraldSword, 1), new Object[]{"  C","  C","  S", 'C', Items.emerald, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyPickaxe, 1), new Object[]{"CCC"," S "," S ", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyAxe, 1), new Object[]{"CC ","CS "," S ", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyAxe, 1), new Object[]{" CC"," CS","  S", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyShovel, 1), new Object[]{" C "," S "," S ", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyShovel, 1), new Object[]{"C  ","S  ","S  ", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyShovel, 1), new Object[]{"  C","  S","  S", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyHoe, 1), new Object[]{"CC "," S "," S ", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyHoe, 1), new Object[]{" CC","  S","  S", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubySword, 1), new Object[]{" C "," C "," S ", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubySword, 1), new Object[]{"C  ","C  ","S  ", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubySword, 1), new Object[]{"  C","  C","  S", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyHammer, 1), new Object[]{"CCC","CCC"," S ", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyMegaHammer, 1), new Object[]{"CCC","CCC"," S ", 'C', blockRuby_Block, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyHamaxe, 1), new Object[]{"RSR","HSA","RSR", 'H', rubyHammer, 'A', rubyAxe, 'S', Items.string, 'R', itemRuby});
		GameRegistry.addRecipe(new ItemStack(rubyBroadsword, 1), new Object[]{"SSS","RRR","III", 'S', Items.string, 'I', Items.stick, 'R', rubySword});
		GameRegistry.addRecipe(new ItemStack(rubyDrill, 1), new Object[]{" C ","CCC"," S ", 'C', itemRuby, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubyMegaDrill, 1), new Object[]{" C ","CCC"," S ", 'C', blockRuby_Block, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(rubySpear, 1), new Object[]{" R ","RSR","III", 'C', itemRuby, 'I', Items.stick, 'R', rubySword, 'S', Items.string});
		GameRegistry.addRecipe(new ItemStack(obsidianPickaxe, 1), new Object[]{"CCC"," S "," S ", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianAxe, 1), new Object[]{"CC ","CS "," S ", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianAxe, 1), new Object[]{" CC"," CS","  S", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianShovel, 1), new Object[]{" C "," S "," S ", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianShovel, 1), new Object[]{"C  ","S  ","S  ", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianShovel, 1), new Object[]{"  C","  S","  S", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianHoe, 1), new Object[]{"CC "," S "," S ", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianHoe, 1), new Object[]{" CC","  S","  S", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianSword, 1), new Object[]{" C "," C "," S ", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianSword, 1), new Object[]{"C  ","C  ","S  ", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(obsidianSword, 1), new Object[]{"  C","  C","  S", 'C', Blocks.obsidian, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(unknownTexturePickaxe, 1), new Object[]{"CCC"," S "," S ", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureAxe, 1), new Object[]{"CC ","CS "," S ", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureAxe, 1), new Object[]{" CC"," CS","  S", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureShovel, 1), new Object[]{" C "," S "," S ", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureShovel, 1), new Object[]{"C  ","S  ","S  ", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureShovel, 1), new Object[]{"  C","  S","  S", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureHoe, 1), new Object[]{"CC "," S "," S ", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureHoe, 1), new Object[]{" CC","  S","  S", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureSword, 1), new Object[]{" C "," C "," S ", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureSword, 1), new Object[]{"C  ","C  ","S  ", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(unknownTextureSword, 1), new Object[]{"  C","  C","  S", 'C', itemUnknown_Texture_Ingot, 'S', Items.blaze_rod});
		GameRegistry.addRecipe(new ItemStack(ultimaPickaxe, 1), new Object[]{"CCC"," S "," S ", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaAxe, 1), new Object[]{"CC ","CS "," S ", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaAxe, 1), new Object[]{" CC"," CS","  S", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaShovel, 1), new Object[]{" C "," S "," S ", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaShovel, 1), new Object[]{"C  ","S  ","S  ", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaShovel, 1), new Object[]{"  C","  S","  S", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaHoe, 1), new Object[]{"CC "," S "," S ", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaHoe, 1), new Object[]{" CC","  S","  S", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaSword, 1), new Object[]{" C "," C "," S ", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaSword, 1), new Object[]{"C  ","C  ","S  ", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaSword, 1), new Object[]{"  C","  C","  S", 'C', blockUltimaBlock, 'S', itemUltimaStick});
		GameRegistry.addRecipe(new ItemStack(ultimaBow, 1), new Object[]{" US","U S"," US", 'U', blockUltimaBlock, 'S', Items.string});
		GameRegistry.addRecipe(new ItemStack(blockRuby_Block, 1), new Object[]{"RRR","RRR","RRR", 'R', itemRuby});
		GameRegistry.addShapelessRecipe(new ItemStack(itemRuby, 9), new Object[]{blockRuby_Block});
		GameRegistry.addRecipe(new ItemStack(blockUnknown_Texture_Block, 1), new Object[]{"UUU","UUU","UUU", 'U', itemUnknown_Texture_Ingot});
		GameRegistry.addShapelessRecipe(new ItemStack(itemUnknown_Texture_Ingot, 9), new Object[]{blockUnknown_Texture_Block});
		GameRegistry.addRecipe(new ItemStack(itemUnknown_Texture_Ingot, 1), new Object[]{"NNN","NNN","NNN", 'N', itemUnknownTextureNugget});
		GameRegistry.addShapelessRecipe(new ItemStack(itemUnknownTextureNugget, 9), new Object[]{itemUnknown_Texture_Ingot});
		GameRegistry.addRecipe(new ItemStack(blockError404Block, 1), new Object[]{"UUU","UUU","UUU", 'U', blockUnknown_Texture_Block});
		GameRegistry.addShapelessRecipe(new ItemStack(blockUnknown_Texture_Block, 9), new Object[]{blockError404Block});
		GameRegistry.addRecipe(new ItemStack(blockCheeseBlock, 1), new Object[]{"CCC","CCC","CCC", 'C', itemCheese});
		GameRegistry.addRecipe(new ItemStack(itemYoullBeDarned, 1), new Object[]{"DTR","ESE","RTD", 'E', Items.ender_eye, 'S', Items.nether_star, 'T', Items.ghast_tear, 'D', Items.diamond, 'R', itemRuby});
		GameRegistry.addRecipe(new ItemStack(itemCheeseStick, 9), new Object[]{"CCC","CSC","CCC", 'C', itemCheese, 'S', Items.stick});
		GameRegistry.addRecipe(new ItemStack(cheeseHelmet, 1), new Object[]{"CCC","C C","   ", 'C', blockCheeseBlock});
		GameRegistry.addRecipe(new ItemStack(cheeseHelmet, 1), new Object[]{"   ","CCC","C C", 'C', blockCheeseBlock});
		GameRegistry.addRecipe(new ItemStack(cheeseChestplate, 1), new Object[]{"C C","CCC","CCC", 'C', blockCheeseBlock});
		GameRegistry.addRecipe(new ItemStack(cheeseLeggings, 1), new Object[]{"CCC","C C","C C", 'C', blockCheeseBlock});
		GameRegistry.addRecipe(new ItemStack(cheeseBoots, 1), new Object[]{"   ","C C","C C", 'C', blockCheeseBlock});
		GameRegistry.addRecipe(new ItemStack(cheeseBoots, 1), new Object[]{"C C","C C","   ", 'C', blockCheeseBlock});
		GameRegistry.addRecipe(new ItemStack(emeraldHelmet, 1), new Object[]{"CCC","C C","   ", 'C', Items.emerald});
		GameRegistry.addRecipe(new ItemStack(emeraldHelmet, 1), new Object[]{"   ","CCC","C C", 'C', Items.emerald});
		GameRegistry.addRecipe(new ItemStack(emeraldChestplate, 1), new Object[]{"C C","CCC","CCC", 'C', Items.emerald});
		GameRegistry.addRecipe(new ItemStack(emeraldLeggings, 1), new Object[]{"CCC","C C","C C", 'C', Items.emerald});
		GameRegistry.addRecipe(new ItemStack(emeraldBoots, 1), new Object[]{"   ","C C","C C", 'C', Items.emerald});
		GameRegistry.addRecipe(new ItemStack(emeraldBoots, 1), new Object[]{"C C","C C","   ", 'C', Items.emerald});
		GameRegistry.addRecipe(new ItemStack(rubyHelmet, 1), new Object[]{"CCC","CDC","   ", 'C', itemRuby, 'D', Items.diamond});
		GameRegistry.addRecipe(new ItemStack(rubyHelmet, 1), new Object[]{"   ","CCC","CDC", 'C', itemRuby, 'D', Items.diamond});
		GameRegistry.addRecipe(new ItemStack(rubyChestplate, 1), new Object[]{"C C","CDC","CCC", 'C', itemRuby, 'D', Items.diamond});
		GameRegistry.addRecipe(new ItemStack(rubyLeggings, 1), new Object[]{"CCC","D D","C C", 'C', itemRuby, 'D', Items.diamond});
		GameRegistry.addRecipe(new ItemStack(rubyBoots, 1), new Object[]{"   ","C C","C C", 'C', itemRuby});
		GameRegistry.addRecipe(new ItemStack(rubyBoots, 1), new Object[]{"C C","C C","   ", 'C', itemRuby});
		GameRegistry.addRecipe(new ItemStack(obsidianHelmet, 1), new Object[]{"CCC","C C","   ", 'C', Blocks.obsidian});
		GameRegistry.addRecipe(new ItemStack(obsidianHelmet, 1), new Object[]{"   ","CCC","C C", 'C', Blocks.obsidian});
		GameRegistry.addRecipe(new ItemStack(obsidianChestplate, 1), new Object[]{"C C","CCC","CCC", 'C', Blocks.obsidian});
		GameRegistry.addRecipe(new ItemStack(obsidianLeggings, 1), new Object[]{"CCC","C C","C C", 'C', Blocks.obsidian});
		GameRegistry.addRecipe(new ItemStack(obsidianBoots, 1), new Object[]{"   ","C C","C C", 'C', Blocks.obsidian});
		GameRegistry.addRecipe(new ItemStack(obsidianBoots, 1), new Object[]{"C C","C C","   ", 'C', Blocks.obsidian});
		GameRegistry.addRecipe(new ItemStack(unknownTextureHelmet, 1), new Object[]{"CCC","C C","   ", 'C', itemUnknown_Texture_Ingot});
		GameRegistry.addRecipe(new ItemStack(unknownTextureHelmet, 1), new Object[]{"   ","CCC","C C", 'C', itemUnknown_Texture_Ingot});
		GameRegistry.addRecipe(new ItemStack(unknownTextureChestplate, 1), new Object[]{"C C","CCC","CCC", 'C', itemUnknown_Texture_Ingot});
		GameRegistry.addRecipe(new ItemStack(unknownTextureLeggings, 1), new Object[]{"CCC","C C","C C", 'C', itemUnknown_Texture_Ingot});
		GameRegistry.addRecipe(new ItemStack(unknownTextureBoots, 1), new Object[]{"   ","C C","C C", 'C', itemUnknown_Texture_Ingot});
		GameRegistry.addRecipe(new ItemStack(unknownTextureBoots, 1), new Object[]{"C C","C C","   ", 'C', itemUnknown_Texture_Ingot});
		GameRegistry.addRecipe(new ItemStack(paladusHelmet, 1), new Object[]{"U U","UUU","U U", 'U', blockUnknown_Texture_Block});
		GameRegistry.addRecipe(new ItemStack(paladusChestplate, 1), new Object[]{"UUU","UUU","U U", 'U', blockUnknown_Texture_Block});
		GameRegistry.addRecipe(new ItemStack(ultimaHelmet, 1), new Object[]{"CCC","C C","   ", 'C', blockUltimaBlock});
		GameRegistry.addRecipe(new ItemStack(ultimaHelmet, 1), new Object[]{"   ","CCC","C C", 'C', blockUltimaBlock});
		GameRegistry.addRecipe(new ItemStack(ultimaChestplate, 1), new Object[]{"C C","CCC","CCC", 'C', blockUltimaBlock});
		GameRegistry.addRecipe(new ItemStack(ultimaLeggings, 1), new Object[]{"CCC","C C","C C", 'C', blockUltimaBlock});
		GameRegistry.addRecipe(new ItemStack(ultimaBoots, 1), new Object[]{"   ","C C","C C", 'C', blockUltimaBlock});
		GameRegistry.addRecipe(new ItemStack(ultimaBoots, 1), new Object[]{"C C","C C","   ", 'C', blockUltimaBlock});
		GameRegistry.addRecipe(new ItemStack(itemCheese, 8), new Object[]{"SSS","SSS","SSS", 'S', itemCheeseStick});
		GameRegistry.addShapelessRecipe(new ItemStack(itemDirtyCheese, 1), new Object[]{itemCheese, Blocks.dirt});
		GameRegistry.addRecipe(new ItemStack(Items.emerald, 1), new Object[]{"NNN","NNN","NNN", 'N', itemEmeraldNugget});
		GameRegistry.addShapelessRecipe(new ItemStack(itemEmeraldNugget, 9), new Object[]{Items.emerald});
		GameRegistry.addRecipe(new ItemStack(itemRuby, 1), new Object[]{"NNN","NNN","NNN", 'N', itemRubyNugget});
		GameRegistry.addShapelessRecipe(new ItemStack(itemRubyNugget, 9), new Object[]{itemRuby});
		GameRegistry.addRecipe(new ItemStack(Blocks.obsidian, 1), new Object[]{"NNN","NNN","NNN", 'N', itemObsidianNugget});
		GameRegistry.addShapelessRecipe(new ItemStack(itemObsidianNugget, 9), new Object[]{Blocks.obsidian});
		GameRegistry.addRecipe(new ItemStack(Items.diamond, 1), new Object[]{"NNN","NNN","NNN", 'N', itemDiamondNugget});
		GameRegistry.addShapelessRecipe(new ItemStack(itemDiamondNugget, 9), new Object[]{Items.diamond});
		GameRegistry.addRecipe(new ItemStack(itemWither_Boss_Spawn_Egg, 1), new Object[]{"SUS","RWR","SUS", 'W', Blocks.skull, 'U', blockUnknown_Texture_Block, 'S', Blocks.soul_sand, 'R', blockRuby_Block});
		GameRegistry.addRecipe(new ItemStack(blockSoulAlter, 1), new Object[]{"DSD","RRR","OOO", 'D', Blocks.diamond_block, 'S', Items.nether_star, 'R', blockRuby_Block, 'O', Blocks.obsidian});
		GameRegistry.addRecipe(new ItemStack(itemGhastBaby, 1), new Object[]{"DTD","TST","DTD", 'D', Items.diamond, 'S', Items.nether_star, 'T', Items.ghast_tear});
		
		GameRegistry.addSmelting(itemCheese, new ItemStack(itemGrilledCheese), 2.0F);
		GameRegistry.addSmelting(itemGrilledCheese, new ItemStack(itemOverdoneCheese), -4.0F);
		GameRegistry.addSmelting(itemOverdoneCheese, new ItemStack(itemBurntCheese), -8.0F);
		GameRegistry.addSmelting(itemDirtyCheese, new ItemStack(itemCheese), -4.0F);
		GameRegistry.addSmelting(blockCheeseOre, new ItemStack(itemCheese), 2.0F);
		GameRegistry.addSmelting(blockNetherCheeseOre, new ItemStack(itemDirtyCheese), 4.0F);
		GameRegistry.addSmelting(blockEndCheeseOre, new ItemStack(itemDirtyCheese), 8.0F);
		GameRegistry.addSmelting(blockRuby_Ore, new ItemStack(itemRuby), 10.0F);
		GameRegistry.addSmelting(blockUnknown_Texture_Ore, new ItemStack(itemUnknown_Texture_Ingot), 25.0F);
		GameRegistry.addSmelting(cheesePickaxe, new ItemStack(itemCheeseStick), 2.0F);
		GameRegistry.addSmelting(cheeseAxe, new ItemStack(itemCheeseStick), 2.0F);
		GameRegistry.addSmelting(cheeseShovel, new ItemStack(itemCheeseStick), 2.0F);
		GameRegistry.addSmelting(cheeseHoe, new ItemStack(itemCheeseStick), 2.0F);
		GameRegistry.addSmelting(cheeseSword, new ItemStack(itemCheeseStick), 2.0F);
		GameRegistry.addSmelting(cheeseHelmet, new ItemStack(itemCheeseStick), 2.0F);
		GameRegistry.addSmelting(cheeseChestplate, new ItemStack(itemCheeseStick), 2.0F);
		GameRegistry.addSmelting(cheeseLeggings, new ItemStack(itemCheeseStick), 2.0F);
		GameRegistry.addSmelting(cheeseBoots, new ItemStack(itemCheeseStick), 2.0F);
		GameRegistry.addSmelting(emeraldPickaxe, new ItemStack(itemEmeraldNugget), 7.0F);
		GameRegistry.addSmelting(emeraldAxe, new ItemStack(itemEmeraldNugget), 7.0F);
		GameRegistry.addSmelting(emeraldShovel, new ItemStack(itemEmeraldNugget), 7.0F);
		GameRegistry.addSmelting(emeraldHoe, new ItemStack(itemEmeraldNugget), 7.0F);
		GameRegistry.addSmelting(emeraldSword, new ItemStack(itemEmeraldNugget), 7.0F);
		GameRegistry.addSmelting(emeraldHelmet, new ItemStack(itemEmeraldNugget), 7.0F);
		GameRegistry.addSmelting(emeraldChestplate, new ItemStack(itemEmeraldNugget), 7.0F);
		GameRegistry.addSmelting(emeraldLeggings, new ItemStack(itemEmeraldNugget), 7.0F);
		GameRegistry.addSmelting(emeraldBoots, new ItemStack(itemEmeraldNugget), 7.0F);
		GameRegistry.addSmelting(rubyPickaxe, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyAxe, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyShovel, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyHoe, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubySword, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyHelmet, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyChestplate, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyLeggings, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyBoots, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyHammer, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyMegaHammer, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyHamaxe, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyBroadsword, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyDrill, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubyMegaDrill, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(rubySpear, new ItemStack(itemRubyNugget), 10.0F);
		GameRegistry.addSmelting(obsidianPickaxe, new ItemStack(itemObsidianNugget), 14.0F);
		GameRegistry.addSmelting(obsidianAxe, new ItemStack(itemObsidianNugget), 14.0F);
		GameRegistry.addSmelting(obsidianShovel, new ItemStack(itemObsidianNugget), 14.0F);
		GameRegistry.addSmelting(obsidianHoe, new ItemStack(itemObsidianNugget), 14.0F);
		GameRegistry.addSmelting(obsidianSword, new ItemStack(itemObsidianNugget), 14.0F);
		GameRegistry.addSmelting(obsidianHelmet, new ItemStack(itemObsidianNugget), 14.0F);
		GameRegistry.addSmelting(obsidianChestplate, new ItemStack(itemObsidianNugget), 14.0F);
		GameRegistry.addSmelting(obsidianLeggings, new ItemStack(itemObsidianNugget), 14.0F);
		GameRegistry.addSmelting(obsidianBoots, new ItemStack(itemObsidianNugget), 14.0F);
		GameRegistry.addSmelting(unknownTexturePickaxe, new ItemStack(itemUnknownTextureNugget), 25.0F);
		GameRegistry.addSmelting(unknownTextureAxe, new ItemStack(itemUnknownTextureNugget), 25.0F);
		GameRegistry.addSmelting(unknownTextureShovel, new ItemStack(itemUnknownTextureNugget), 25.0F);
		GameRegistry.addSmelting(unknownTextureHoe, new ItemStack(itemUnknownTextureNugget), 25.0F);
		GameRegistry.addSmelting(unknownTextureSword, new ItemStack(itemUnknownTextureNugget), 25.0F);
		GameRegistry.addSmelting(unknownTextureHelmet, new ItemStack(itemUnknownTextureNugget), 25.0F);
		GameRegistry.addSmelting(unknownTextureChestplate, new ItemStack(itemUnknownTextureNugget), 25.0F);
		GameRegistry.addSmelting(unknownTextureLeggings, new ItemStack(itemUnknownTextureNugget), 25.0F);
		GameRegistry.addSmelting(unknownTextureBoots, new ItemStack(itemUnknownTextureNugget), 25.0F);
		GameRegistry.addSmelting(paladusHelmet, new ItemStack(itemUnknown_Texture_Ingot), 500.0F);
		GameRegistry.addSmelting(paladusChestplate, new ItemStack(itemUnknown_Texture_Ingot), 500.0F);
		GameRegistry.addSmelting(Items.diamond_pickaxe, new ItemStack(itemDiamondNugget), 7.0F);
		GameRegistry.addSmelting(Items.diamond_axe, new ItemStack(itemDiamondNugget), 7.0F);
		GameRegistry.addSmelting(Items.diamond_shovel, new ItemStack(itemDiamondNugget), 7.0F);
		GameRegistry.addSmelting(Items.diamond_hoe, new ItemStack(itemDiamondNugget), 7.0F);
		GameRegistry.addSmelting(Items.diamond_sword, new ItemStack(itemDiamondNugget), 7.0F);
		GameRegistry.addSmelting(Items.diamond_helmet, new ItemStack(itemDiamondNugget), 7.0F);
		GameRegistry.addSmelting(Items.diamond_chestplate, new ItemStack(itemDiamondNugget), 7.0F);
		GameRegistry.addSmelting(Items.diamond_leggings, new ItemStack(itemDiamondNugget), 7.0F);
		GameRegistry.addSmelting(Items.diamond_boots, new ItemStack(itemDiamondNugget), 7.0F);
		GameRegistry.addSmelting(ultimaPickaxe, new ItemStack(itemUltimaStick), 2.0F);
		GameRegistry.addSmelting(ultimaAxe, new ItemStack(itemUltimaStick), 2.0F);
		GameRegistry.addSmelting(ultimaShovel, new ItemStack(itemUltimaStick), 2.0F);
		GameRegistry.addSmelting(ultimaHoe, new ItemStack(itemUltimaStick), 2.0F);
		GameRegistry.addSmelting(ultimaSword, new ItemStack(itemUltimaStick), 2.0F);
		GameRegistry.addSmelting(ultimaHelmet, new ItemStack(itemUltimaStick), 2.0F);
		GameRegistry.addSmelting(ultimaChestplate, new ItemStack(itemUltimaStick), 2.0F);
		GameRegistry.addSmelting(ultimaLeggings, new ItemStack(itemUltimaStick), 2.0F);
		GameRegistry.addSmelting(ultimaBoots, new ItemStack(itemUltimaStick), 2.0F);
		GameRegistry.addSmelting(ultimaBow, new ItemStack(itemUltimaStick), 2.0F);
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		
	}
	
	public static CreativeTabs tabModdingSchool = new CreativeTabs("tabModdingSchool"){
		@Override
		public Item getTabIconItem(){
			return new ItemStack(blockDaRubyMiner360_Skull).getItem();
		}
	};
	public static CreativeTabs tabModdingSchoolTools = new CreativeTabs("tabModdingSchoolTools"){
		@Override
		public Item getTabIconItem(){
			return new ItemStack(obsidianSword).getItem();
		}
	};
	public static CreativeTabs tabModdingSchoolFoods = new CreativeTabs("tabModdingSchoolFoods"){
		@Override
		public Item getTabIconItem(){
			return new ItemStack(itemCheese).getItem();
		}
	};
	public static CreativeTabs tabModdingSchoolMaterials = new CreativeTabs("tabModdingSchoolMaterials"){
		@Override
		public Item getTabIconItem(){
			return new ItemStack(itemRuby).getItem();
		}
	};
	public static CreativeTabs tabModdingSchoolSpawnEggs = new CreativeTabs("tabModdingSchoolSpawnEggs"){
		@Override
		public Item getTabIconItem(){
			return new ItemStack(itemEnder_Dragon_Spawn_Egg).getItem();
		}
	};
}
